### ISSUE TITLE
User's none visible fields show up

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#10]
For the most part when I have not marked a person's field as [ ] This Field Is Visible it seems to not be showing up but for this one user the fields display on their profile.

<img width="1226" alt="screen shot 2015-11-04 at 3 41 23 pm" src="https://cloud.githubusercontent.com/assets/14365107/10955714/d10b8222-830a-11e5-8374-41ec77154ef1.png">

**Comment by samuelreh** [comment]
This is kinda confusing. We display those fields because you're logged in right? If you weren't logged in, we wouldn't display those. Am I missing something?

**Comment by lisajoytrick** [comment]
um.... you're almost right. I was seeing these fields when I was logged in but not when I'm not logged in. But, I think the field visibility still needs to be tweaked a little because regular users (non admin) can see all of each another's private info still.

So...
> "This Field Is Visible" *if selected* should mean that everyone can see the data whether or not logged in (this is working well)
> "This Field Is Visible" *if left blank* should mean that only the user themselves can see/edit the data  in the "edit profile" view + admin can see it when they click on edit from the admin > manage users area

Hopefully that's clearer

**Comment by samuelreh** [comment]
Should be good now.
