### ISSUE TITLE
Remove contact button from host profile

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe#106]
if users send a message to others using the 'contact [host]' button on the host profile page, we don't see the message string in the 'view experiences' panel. Hence, it's difficult for us to keep track. 

Can we remove the 'contact [host]' button from the host profile page?

**Comment by AndieFro** [comment]
It's important that admin are still able to see a contact button so we can still contact kudoers
Also that the contact button is not removed from hosts' experience listings - just their profile

**Comment by mkasdani** [comment]
A lot of hosts are still missing their calendars, so Kudoers have used 'contact' button A LOT. Also when the timing doesn't work, we still let them to negotiate on timing (sometimes Hosts are open to this), this is also done through 'contact' button messaging.

I think we need to keep this button.

**Comment by AndieFro** [comment]
@mkasdani we aren't going to remove the button from the experience page, just from the profile page. We aren't able to view any of the messages that get seent via the contact button on host profile but we are when a Kudoer messages a host via the experience page

![image](https://cloud.githubusercontent.com/assets/16580556/13154893/0d825c3a-d630-11e5-968d-694566f2421c.png)
