### ISSUE TITLE
Using an email address for multiple accounts

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#107]
Right now it's not possible to use the same email address for multiple sharetribe accounts. This is an issue because some circle members are also hosts (or have created an account for another reason).

Even when we have deleted a previous user in order to try and add it to a Kudoer as their circle Sharetribe is rejecting the email.

![image](https://cloud.githubusercontent.com/assets/16580556/13154074/f780d186-d62b-11e5-9088-5ac3cbb67034.png)

We've tried adding Michelle to Holly's circle and the system won't accept her email even though Michelles previous account has been deleted. A temporary solution is to add a different email account but this won't be feasable permanently.

I've also had this problem adding Patrice's email - Patrice has been added to Jordana's circle and I can't add her proper email to her account as a host now. (patrice's email in her host profile is wrong and now she would not get any messages if she were to re-open her experience).

![image](https://cloud.githubusercontent.com/assets/16580556/13154430/c4a23c6c-d62d-11e5-81a9-a24157e08267.png)
Patrice's email in Jordana's account

![image](https://cloud.githubusercontent.com/assets/16580556/13154483/01929b94-d62e-11e5-9f4c-6f082901c521.png)

I can't delete the wrong email address in Patrice's account until I can add her new one

**Comment by mkasdani** [comment]
Yesterday, we were out recruiting two Kudoers at the same time. We thought one Kudoer could be a Circle for the other one. But since we can't use the same email in two places in the catalogue (in this case: two Kudoers account), we can't save the Circle/ Kudoer email to another one Kudoer's account.

**Comment by jonaspiet** [comment]
can we add a gmail address and set up forwarding?


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by AndieFro** [comment]
@jonaspiet my opinion is creating a whole new email account is a really an impractical work around. Plus I see the extra step creating the possibility for something to go wrong in the Kudoer/host not getting emails from the site.

**Comment by jonaspiet** [comment]
@samuelreh is this a quick fix?

**Comment by AndieFro** [comment]
@jonaspiet my opinion is creating a whole new email account is a really an impractical work around. Plus I see the extra step creating the possibility for something to go wrong in the Kudoer/host not getting emails from the site.

**Comment by samuelreh** [comment]
Not sure if this solved it, but for some email providers (like gmail), you can simply add a plus or period in the email address. For instance, I can use samuelreh+1@gmail.com, samuel.reh@gmail.com or samuelreh+kudoz@gmail.com. These all forward to my email address.

**Comment by samuelreh** [comment]
It looks like both gobaci.com and the gmaill acount use google mail servers so it should work fine.

**Comment by samuelreh** [comment]
You can check emails by using: http://www.checktls.com/perl/TestReceiver.pl

You can try "michelle.owen+1@gobaci.com" and it should be valid :smile:

**Comment by jonaspiet** [comment]
thanks!


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet
