### ISSUE TITLE
Banned users?

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#109]
I think I accidentally banned myself (a second account I created for showing examples and screenshots). Is there anyway of undoing this? 

![image](https://cloud.githubusercontent.com/assets/16580556/13263943/bd96310c-da20-11e5-8081-3668056fe2fe.png)

**Comment by jonaspiet** [comment]
im looking in the backend but can't see anything unusual. which email
addresss is this user?


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by AndieFro** [comment]
It's an old emil address fornever@live.ca

**Comment by samuelreh** [comment]
@AndieFro unbanned now
