### ISSUE TITLE
Calendar Dates getting deleted

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#112]
Several of the hosts that recieved the email asking to add dates into the calendar have reported that they did put dates in the Calendar. Several team members watched these hosts put the dates in the calendar and save them so we are certain it is not a user error.

Examlpes: Anna Wexler (Puppy Playtime), Alexandre Lima (Turning Electricity on), Thomas Howell (mixing creative cocktails)

@jonaspiet It's causing a bit of a problem because hosts are calling and asking us why they are getting these reminders to do something that they've already done and we feel kinda unprofessional.

**Comment by AndieFro** [comment]
@jonaspiet 
I got another phone call from a host this morning: Claire Roberts: bellydancing. The last 2 times the reminder email went out she checked and her dates had been deleted even though she had put dates in.

**Comment by jonaspiet** [comment]
@samuelreh can you make this top priority pls?


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by AndieFro** [comment]
@samuelreh 
Two more hosts have reported this bug to me today: Alexander Dirksen and Sheila Maier. I'm not sure when the dates got deleted so maybe they won't get deleted again but wanted to record which hosts it happened to.

**Comment by AndieFro** [comment]
On Tuesday this happened to Nathan To. as he was making his experience the calendar was deleted few times. Even after he saved it and it looked like there was dates there, Shannon tried booking him and there weren't dates there so she tried to arrange a time through messaging.

**Comment by AndieFro** [comment]
Sharing an email from host Claire I got this morning @jonaspiet @samuelreh 

Hello Kudoz folks!
I talked to Andie when I got this message, because I had populated weekly dates, which seemed to have magically disappeared.  It was actually the second time I had received a message like this, and found my calendar had been wiped.  We agreed it was weird, and she repopulated it for me, and I confirmed I could see the listings in my calendar.  

This morning, I went to update my calendar, and noticed that it is wiped again.  Normally I mark myself as available on Thursday nights at 7:30pm.
I will refrain from re-populating it again, in case leaving it's helpful to the web dev / IT folks to see it as it is currently when they are troubleshooting.

Good luck sorting it out, and let me know if there's anything I can do to be helpful.
Cheers,
-Claire

**Comment by AndieFro** [comment]
Perhaps something else going on with Calendars. Alexander Dirksen of the Wonk Walk experience has reported to me before that his dates were deleted sometime between creating his experience and the bi-weekly email going out. Today Janey was trying to request the experience with a Kudoer and not only are the times gone, but we aren't even able to send a message to the host
![image](https://cloud.githubusercontent.com/assets/16580556/13931989/428ee80c-ef63-11e5-9349-2272d8c27e94.png)

https://catalogue.kudoz.ca/en/listings/237

**Comment by samuelreh** [comment]
@jonaspiet @AndieFro I think I fixed the problem, but I'm not 100% sure. It's kind of hard to reproduce the exact problem (which seems weird to me since so many hosts are experiencing it).

I don't think we should send out the missing availabilities email tomorrow (maybe we can send it next week instead) once we're sure the application is fixed.
