### ISSUE TITLE
Calendar on users profile

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#114]
@jonaspiet perhaps we could plan this out together a little more in person when you are here. 

We think there should be a calendar, or in the least a list of experiences you have confirmed that appears on a users profile. Once or twice hosts have asked me to confirm when they booked their experiences for. In one case this week a host has double booked their Kudoz experience with 2 different Kudoers. Also, I believe this will be very helpful for Kudoers to be able to check up on their Kudoz 'schedule'.

**Comment by AndieFro** [comment]
Maybe this is related to issue #100?

**Comment by jonaspiet** [comment]
@samualreh can you give a rough estimate?
simplest version:
user sees on profile which experiences are booked / requested, and cancel button shows up there.

rationale: so that users have this info in one place, and cancel through the button - so we get to know and can offer an alternative.

**Comment by samuelreh** [comment]
See #129
