### ISSUE TITLE
confirmation when sharing phone numbers

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#115]
Some user feedback

"Hey Kudoz,
I'm happy to share my phone number with Jordana, I just wasn't sure how to do that. When I click the "share your phone number" button it takes me back to the Kudoz catalogue page.
Should I send Jordana a note or is there another way you'd like me to do this?
Take care,
Sarah"

This is not the only feedback I've had about this, John Woods and a few other hosts that are on the team have reported this.

It would be nice to see a confirmation page that my number has been shared so I know I don't have to do anything else. Thanks.

**Comment by AndieFro** [comment]
Hi @jonaspiet . Not a super pressing fix but this is confusing some hosts

**Comment by samuelreh** [comment]
Thanks @AndieFro 
I've added a notice on the catalogue page that says "Great! We've shared your number!" after they share it.
