### ISSUE TITLE
Market place unavailable when trying to edit Kudoers profile

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#116]
Since last night, Yani has been trying to update the profile including text, youtube link and pictures for Umete. Every she clicks 'save' She sees the 'marketplace unavailable' page and when she visits the profile again the information did not save. She has tried restarting her computer and using a different browser but the problem persists.

The same problem happened when trying to upload Kudoer Mandy's profile picture.

**Comment by AndieFro** [comment]
I have tried editing Umetes profile as well and got this message

![image](https://cloud.githubusercontent.com/assets/16580556/13440579/90b9a2fe-dfa7-11e5-884a-b747ae08405e.png)

**Comment by AndieFro** [comment]
This seems to be site wide right now, I can't edit hosts or even my personal profile wight now @samuelreh could this be because you are making updates to the profile right now?

**Comment by samuelreh** [comment]
Woops, sorry about that. Should be fixed now.

**Comment by AndieFro** [comment]
Awesome. Thanks @samuelreh !!!!!
