### ISSUE TITLE
Don't allow users to book their own experiences.

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#118]
@samuelreh the admin: 'view experiences' page is down

I get this page when I visit admin> view experiences
https://catalogue.kudoz.ca/en/admin/communities/1/transactions?direction=desc&sort=last_activity

![image](https://cloud.githubusercontent.com/assets/16580556/13444402/efad09d2-dfba-11e5-888c-e38307eb7867.png)

**Comment by samuelreh** [comment]
Hmmm. Looks like someone booked their own experience... We should have a check so this can't happen.

**Comment by AndieFro** [comment]
ah, yes. yani was testing what would happen if she booked something in the past
