### ISSUE TITLE
Filter by categories not working well

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe#119]
There are experiences that aren't showing up under the categories that they are sorted under.  This is an issue because a lot of users browse the catalogue by going through categories so experiences are going completely un-noticed. 

There are multiple instances of this, I'm just using the example of 'basic Cake Decorating'
![image](https://cloud.githubusercontent.com/assets/16580556/13471376/273370ee-e065-11e5-9471-98d8b91e0b40.png)

I've saved it under the category 'food'. (ideally it would go under 'food' AND 'making things')
![image](https://cloud.githubusercontent.com/assets/16580556/13471334/f7dc087e-e064-11e5-99f9-fde390bc9510.png)

When we visit the food category basic cake decorating is nowhere to be found
![image](https://cloud.githubusercontent.com/assets/16580556/13471369/22dac600-e065-11e5-8715-d126dd0791c0.png)

**Comment by samuelreh** [comment]
This is fixed, right? Try again, you should see Cake Decorating under "Food".
