### ISSUE TITLE
Categories - lost & can't reapply

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#12]
It seems that all the experiences have lost their categorization. 

I don't really mind because it would be a good idea for us to review our categories and reorganize the experiences a bit, but I am not able to apply a category to an experience without creating a new experience. 

<img width="1041" alt="screen shot 2015-11-04 at 5 01 39 pm" src="https://github-cloud.s3.amazonaws.com/assets%2F14365107%2F10957066%2Fcbe90084-8315-11e5-9e62-66379f35a717.png">

**Comment by samuelreh** [comment]
Wooohoo! I fixed it!
