### ISSUE TITLE
Sharetribe unchecking the "crim check" box in users listings

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#123]
Both this week and last week when I was going over numbers for the dashboard I noticed some of the users that I had previously check "crim check" for had been un-checked. I made a list of all users I noticed this for today.

Katelyn Sieb
Candice Gunderson
Julian Avelino
Thomas Howell
Justin Albay
Katherine Allen
Andie Froese
John Woods

this tick box
![image](https://cloud.githubusercontent.com/assets/16580556/13534813/d6dc36f2-e1eb-11e5-8e58-40c2422970f3.png)

**Comment by AndieFro** [comment]
I've manually re-checked these hosts but I'm worried it will just happen again next week

**Comment by jonaspiet** [comment]
@samuelreh could you look into this?

**Comment by samuelreh** [comment]
@AndieFro this should be fixed now, thanks for finding.
