### ISSUE TITLE
change action on 'cancel' buttton

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe#124]
When host cancels an booked experience (by hitting 'cancel' button in the booking confirmation message), we want a message to go to Kudoz admins. NOT directly to Kudoers.

Rationale: so we can get in touch with the Kudoer with an alternative experience, instead of just cancelling it, hoping we can rebok it.
![screenshot_2016-03-07_08 35 08_720](https://cloud.githubusercontent.com/assets/11308069/13577598/02a84416-e448-11e5-9eff-1f2e42941db9.png)

@samuelreh probably a quick one - please prioritize this one!

**Comment by samuelreh** [comment]
I'm a little confused, It doesn't look like we send any emails when a host cancels an experience after it has been booked.

However, we do "Message" their sharetribe Inbox. Is this what you want removed? Or are we talking about different flows.

**Comment by jonaspiet** [comment]
yes - we want the 'message' in their inbox removed.
So that just admins gets an email. So that we can send a message to kudoers
with alternatives, rather then just the cancellation




*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
![img_20160309_101159](https://cloud.githubusercontent.com/assets/128012/13645386/a8d2e47a-e5df-11e5-8524-b084dd0a76ff.jpg)
