### ISSUE TITLE
Experience start time doesn't match (between kudoer confirmation / host reminder, sent at booking)

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe#131]
Host and Kudoer receive a different start time for the same booking, in the booking confirmation (Kudoer) and reminder (host). We used an admin account to book this experience, for Tue March 16 at 4.30PM.

The Kudoer confirmation says it's confirmed at 4.30PM (this is correct). But the email reminder that goes out to the host (in this case: us) shows a different time (4PM). In the back-end of the admin account > View Experiences, the experience is showed at the wrong time (4PM).

Confirmation for Kudoer:
![screenshot 2016-03-11 07 58 03](https://cloud.githubusercontent.com/assets/16656508/13707624/64c7691e-e75f-11e5-9284-e262c24d5ee5.png)

Reminder for Host:
![screenshot 2016-03-11 07 58 17](https://cloud.githubusercontent.com/assets/16656508/13707669/9e41bcd0-e75f-11e5-9da2-1043ece3af8b.png)

Back-end admin:
![screenshot 2016-03-11 08 17 10](https://cloud.githubusercontent.com/assets/16656508/13708098/ae43aaa6-e761-11e5-87d6-f1587c03880b.png)

**Comment by samuelreh** [comment]
Looks like a double booking. Closing for now.
