### ISSUE TITLE
Giving feedback to Kudoers/ Hosts/ Admin and vice versa

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe#143]
Right now, the only way that each user (Kudoer/ Host/ Kudoz admin) can give feedback to each other is through marking an experience as done. This has posed a challenge because many experiences were booked through messaging. Because the Kudoz team has to do **manual** checking on Highrise when something is agreed and then book the experience for users (by clicking 'book this experience for a user'), the Kudoz team has sometimes fell behind in terms of booking an experience through this way, and experience has happened, thus there's no more chance to leave feedback (Kudoer to Hosts and vice versa).

Can we have a feature that will enable Hosts/ Kudoers to give each other feedback without marking an experience as done?

This is also a much needed feature for admin, since we're starting to share with Kudoers/ Hosts stories of change (for impact measurement) that we have collected to ask them to accept/ reject it.  It doesn't have to be called "Feedback", it can also be a field for "Significant Moments". Right now there's no way we can display that in Kudoers/ Hosts Profile.

**Comment by jonaspiet** [comment]
This is two different features:
1) Admin can give feedback
2) we need to find a way to make it impossible to agree on an experience without formally booking it.

As for the first - we can build it but it has lower priority.

We'll have to solve the second thing before people start paying. It will completely fuck up our system, as we don't know it is happening (safety risk) and users wouldn't pay for experiences. This is something I want to discuss with @samuelreh. Any thoughts on how to do this?

**Comment by mkasdani** [comment]
In AirBnB, the website automatically blocks out the details of address/ date/ etc... Their website detects certain words that indicate people are doing booking not through AirBnB system to avoid paying 10% commission fee.

As for feedback giving: it is currently the top priority for the Reflection team (both Hosts and Kudoers). Is there any shortcut for this? If not, how do we fake it for now?

**Comment by samuelreh** [comment]
hmmmm, what if we just don't show listings unless they have availabilities.

**Comment by mkasdani** [comment]
That will make quite a number of experiences disappear, because not all Hosts keep their calendars updated. I say, maybe 50% are booked through messaging.

**Comment by lisajoytrick** [comment]
This has been fixed because all experience booked in messaging are created by admin as a transaction/experience.
