### ISSUE TITLE
entire experiences having data deleted

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#144]
occasionally when we've inducted a new host recently all the data we have put into their experience get's deleted.

Most recent examples are give MCing a try  by Meaghan Taylor Reid and Paint and Chat by Helen and Raminder. 

Interesting bit about this is it usually happens when the experience is brand new, we've just created it. Also when I try to repopulate it, Chrome usually remembers what went in the fields from previous experiences but NOT for these ones.

**Comment by AndieFro** [comment]
This just happened to Laura and it happened again to Charlotte last night. Laura the experience listing was her own, a new one and Charlotte while she was inducting Maxine.

I think it happens because we save a new listing and go into edit again too soon?

**Comment by AndieFro** [comment]
This just happened to a host who I asked to put up a second experience on his own
@samuelreh can you take a look at this asap! It's really bad if all new experiences aren't being saved!

![image](https://cloud.githubusercontent.com/assets/16580556/14031434/13a27810-f1ca-11e5-8669-477a396c6bf1.png)

**Comment by samuelreh** [comment]
weird, i'll take a look.

**Comment by samuelreh** [comment]
@AndieFro which listings?

**Comment by AndieFro** [comment]
Kickin it Up - The Art of Muay Thai (Kick it Out Part 2)
Haida Experience
Come Kick a Ball!
Round and Round we go: Oval Walking
What your favourite music says about you
Paint and Chat: learn about your disability
Give MC-ing a try!

**Comment by AndieFro** [comment]
For most of them we noticed right away, while we were still with the host and we put all the data back.
Kickin it Up - The Art of Muay Thai (Kick it Out Part 2) AND Give MC-ing a try! are still empty

**Comment by samuelreh** [comment]
@AndieFro you're right, this doesn't work at all.

**Comment by samuelreh** [comment]
@AndieFro this is fixed now.

**Comment by AndieFro** [comment]
Excellent! Thanks!
