### ISSUE TITLE
I (as a host) received the same request for the same experience 3 times (email and text messages)

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe#146]
I had an experience booked by a Kudoer (my experience: https://catalogue.kudoz.ca/en/listings/250). I received 3 email notifications, 3 messages in Sharetribe and  and 3 text messages, all with the same details. 

From the back-end of Sharetribe, there's also 3 requests of the same experiences.

Screenshot of the Sharetribe messages:
![screenshot 2016-03-29 16 15 11](https://cloud.githubusercontent.com/assets/16656508/14127085/3cec1b78-f5ca-11e5-9b5c-583472fb2951.png)

Screenshot of the content in Sharetribe message:
![screenshot 2016-03-29 16 15 18](https://cloud.githubusercontent.com/assets/16656508/14127096/4ab25ba0-f5ca-11e5-8165-e604d3f76c52.png)

Screenshot of the sms notification:
![2016-03-29 23 16 08](https://cloud.githubusercontent.com/assets/16656508/14127115/728c1026-f5ca-11e5-930f-0d47b7513222.png)

Screenshot of the back-end of Sharetribe.
![screenshot 2016-03-29 16 32 14](https://cloud.githubusercontent.com/assets/16656508/14127882/52952e82-f5d0-11e5-9b84-a41341f20613.png)

**Comment by lisajoytrick** [comment]
@mkasdani What are the chances that the kudoer accidentally booked you multiple times? Maybe they pressed the submit request buttons several times? I haven't seen this come up before so I'm suspecting it's user initiated. I think an easy way for us to cancel the extra bookings if needed might be the solution?
