### ISSUE TITLE
unique reply email addresses for sharetribe messages

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#147]
Issue: When a host or kudoer gets a message sent through the catalogue, they reply in their email platform and their reply is sent to hello@kudoz.ca instead of the intended recipient. 

Suggested improvement: Messages are sent with a unique identifier that routes them back through our catalogue (i.e.: airbnb)  - The unique identifier should be the same if a user replies from any of the email addresses associated with the sharetribe account.
<img width="753" alt="screen shot 2016-03-30 at 1 06 48 pm" src="https://cloud.githubusercontent.com/assets/14365107/14155920/add20c04-f678-11e5-861c-74e289650469.png">

**Comment by samuelreh** [comment]
After reviewing a bit, our email provider has an incoming API that can be setup similar to the AirBnb functionality you're looking for, time estimate would be about 2.5 hrs.
