### ISSUE TITLE
sorting user data- question

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#148]
I would like to have an easy way to sort users in a CSV file from our sharetribe admin panel. Currently I can copy and past the user page into a spreadsheet but it copy over the checkbox data (requesting/booking allowed) or the user type data... what I want to be able to do is sort by user type or and by requesting/booking, etc.

Suggestions?

**Comment by samuelreh** [comment]
Export user CSV data

**Comment by lisajoytrick** [comment]
this was resolved by using mixpanel but our only issue is some missing users in mixpanel (see email)

**Comment by lisajoytrick** [comment]
Hey Sam: opening this back up because we still need a user export in catalogue so we can get not only the list of users & their profile data but also their account data (ie: emails, user type (host/kudoer) and if they are allowed to request or book.

**Comment by samuelreh** [comment]
This is up on prod now.

**Comment by lisajoytrick** [comment]
seems like the columns might be named incorrectly? Can you check the column headings? Seems like they are off by one to the right?

**Comment by samuelreh** [comment]
@lisajoytrick good find. Fixed now.
