### ISSUE TITLE
moving placeholder text

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#150]
Users are finding that it's difficult when the placeholder text (which is meant to be a guide for them) disappears when they start typing. 

Fix: Let's put placeholder text to the right of a text field in the white space instead of inside the box so it remains available to them. Keep the lighter grey colour and italic (css) associated with the current design.

**Comment by samuelreh** [comment]
I put the text right below the field title since that was the easiest.

**Comment by lisajoytrick** [comment]
Hey sam,
This looks good. Just a couple minor style changes. Can the placeholder text be #c3c3c3 instead of black. Other adjustments noted below:

<img width="1074" alt="screen shot 2016-04-05 at 11 48 56 pm" src="https://cloud.githubusercontent.com/assets/14365107/14308283/00cce21a-fb8a-11e5-8e2c-d8fa92f30e51.png">
