### ISSUE TITLE
Add option to skip emails to admin booking

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#153]
Please provide an estimate for this feature:
From the admin booking screen, can we have an options to skip confirmation and reminder emails? 

This would be for used for bookings 
- we are adding after they happen
- when we are rescheduling on their behalf 
- when they've made new arrangements via messaging and we're adding the details to prompt feedback

![skip-emails](https://cloud.githubusercontent.com/assets/14365107/14392455/4642b1d8-fd76-11e5-8098-13e9a90a81f8.png)

**Comment by samuelreh** [comment]
about 1/2 hour

**Comment by lisajoytrick** [comment]
approved
