### ISSUE TITLE
Cancelling experiences - improvements 

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#154]
Currently we have several issues with the cancellation process that I want to run by you for suggested enhancements.

process: We are doing cancellations by using the skeleton key from a users experience page. This is working (although a bit more time consuming that doing cancellations from the admin transaction page) but we have three issues: 
1. We don't always want users to get the cancellation email   

2. We don't want users to be able to give feedback when they cancel. Also, we want all users who complete an experience to do feedback so skipping it should not be an option. The system allows them to as this -as it is used for the host to say why they are cancelling... but using the feedback feature for cancellation reason isn't great as it shows up on the users profile. Better to use regular messaging.

3. The screen you see when you cancel or mark as done is very similar which is a bit confusing

suggested fix for 1. 
**Add option to skip emails to cancellation**
From the admin panel when we cancel a transaction can we have the option to skip the cancellation messages that go out by email? This would be used when an experience has been requested or booked on accident or we are rescheduling on a user's behalf.
similar to "Add option to skip emails to admin booking #153"

suggested fix for 2. & 3.
show a different screen depending on whether cancellation button is pressed or "mark as done" with no feedback skip option and a stealthy hard to notice skip cancellation emails option 
![cancellation_changes](https://cloud.githubusercontent.com/assets/14365107/14395063/5ee0f1d8-fd84-11e5-8dd8-2686f7968e30.png)

**Comment by samuelreh** [comment]
Things to do here:
1. Add option to cancel from admin (with option to skip email). 1 hr
2. Remove ability to choose canceling or completing after clicking link 0.75 hr
3. Remove ability to skip feedback when completing 0.25 hr
4. Remove ability to give feedback when cancelling 0.25 hr

I'd say about 2.25 hrs total

**Comment by samuelreh** [comment]
@lisajoytrick this is done. Cancellations don't actually send out any emails right now (except to the admin).
