### ISSUE TITLE
mixpanel expansion

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#157]
Can you modify Mixpanel so it tracks changes on all fields (profile for kudoer & host + experience listings?) Right now it only tracks changes on the “about me field” 

<img width="641" alt="screen shot 2016-04-12 at 11 23 58 am" src="https://cloud.githubusercontent.com/assets/14365107/14471805/1685f93c-00a5-11e6-80b7-0d1841b3b6f8.png">

**Comment by samuelreh** [comment]
@lisajoytrick sure, would you like to have one event called "Profile Changed" which has properties for each field that's changed (new_about_me, old_about_me, new_profile_video, old_profile_video) or would you rather have an event for each property that's changed (Profile Video Changed)?

**Comment by lisajoytrick** [comment]
I'm not sure. Which ever is easier while also allowing us to see the detail we need which is the specific field that has been change and what the old version vs the new version is.
