### ISSUE TITLE
allow html markup in fields

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#158]
We would like to allow html markup in fields so that we can create hyperlinks. Right now we would specifically like to have links in our placeholder/instructions.

_*also, just a note that when I tried to use html mark on up the example below, the whole field & content area disappeared from the users' view of the profile. When I removed the html it reappeared at the bottom of the profile and I'm not able to put it back into position. It doesn't seem to be following it's order as per the admin "persons fields" list
_
<img width="636" alt="screen shot 2016-04-12 at 1 32 41 pm" src="https://cloud.githubusercontent.com/assets/14365107/14474774/80dc9c24-00b3-11e6-87c0-fd4420f25163.png">

**Comment by samuelreh** [comment]
@lisajoytrick, HTML in the placeholder seems to work for me. However, you're right about the ordering being broken. I'll see if I can fix that.

**Comment by samuelreh** [comment]
ordering is fixed now too.
