### ISSUE TITLE
Creating a URL that directs a user into editing their profile

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#16]
How can I make a url that will go into any specific users profile?

What I want is a link like this...  http://www.kudoz.ca/en/lisajoytrick/settings/profile where instead of my username it's something like http://www.kudoz.ca/en/{username}/settings/profile

**Comment by samuelreh** [comment]
You want me to add an interpolation for a link to the user's profile somewhere in en.yml? Which line?

**Comment by lisajoytrick** [comment]
I'm hoping to use the link in the welcome email (button 3) http://www.kudoz.ca/en/admin/communities/1/edit_welcome_email

**Comment by samuelreh** [comment]
Added an interpolation and changed this in welcome the email.
