### ISSUE TITLE
Receiving the reminder for feedback (again)

### ISSUE THREAD

**Issue by mkasdani** [InWithForward/sharetribe#160]
I left a feedback for Shannon Bromley a few weeks ago, using Profile Builder's account (this account is used by multiple people, with different email accounts). I left the feedback by clicking an email that I received in my inbox. 

The feedback has gone out, as you can see here from Shannon B's profile page (it's pending until she confirms it)
![screenshot 2016-04-14 12 41 41](https://cloud.githubusercontent.com/assets/16656508/14541317/3df2febc-023e-11e6-9c3d-ba627a1418f1.png)

But today, I received another email, reminding me to leave a feedback to Shannon B, for the same experience:
![screenshot 2016-04-14 12 39 10](https://cloud.githubusercontent.com/assets/16656508/14541333/538b6886-023e-11e6-8ede-bc9a3e6acb17.png)

**Comment by jonaspiet** [comment]
thanks for documenting @mkasdani.
is this perhaps the experience that was booked 3 times? Could that be a reason?

**Comment by mkasdani** [comment]
I checked the back-end of Profile Builders. That's correct, there's double booking from Shannon B.
![screenshot 2016-04-15 10 19 06](https://cloud.githubusercontent.com/assets/16656508/14569397/60fb8798-02f3-11e6-8a34-ef1a70878786.png)
