### ISSUE TITLE
Reminder email timing

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#17]
Currently the "reminder email" arrives as soon as the booking is confirmed instead of (or maybe in addition too?) 48 hours before experience. At the same time, the requester also receives a confirmation email. 

1) Can we add the content of "the reminder email" to "the confirmation email" so that there is only one email at this point 
2) + can we change the timing of the reminder email to only arrive 48 hours before an experience?

screen shot refers to 1)
<img width="908" alt="screen shot 2015-11-05 at 3 50 09 pm" src="https://cloud.githubusercontent.com/assets/14365107/10986647/ce31b11c-83e0-11e5-9083-b618679eadba.png">

**Comment by samuelreh** [comment]
This is done
