### ISSUE TITLE
Adding user "roles" to Sharetribe

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#20]
*Sam, we're working on flushing out this request before we hand it over*

*Feature part A - profile types*
> User creates catalogue.kudoz.ca account + confirms email
> User chooses to set up a Host Profile or Kudoer Profile (current profile template is host profile)
> Admin can create persons-fields that are applicable for both profile types or just one profile type

*Feature part B - profile types dashboards*
Part of the profile is static content (name, address, about me, etc) and part of the profile is a dashboard view of your participation within Kudoz. 
> For a host profile the dashboard would display # of experiences hosted, reviews, & badges ????
> For the kudoer profile the dashboard is more complex, displaying stats & updates about their choices, their checkin & checkout data from the mobile app, media from experiences, etc.

**Comment by lisajoytrick** [comment]
Hey Sam, we are going to have this feature all planned out in the next couple days but to start with I've sketched out what the first few signup screens should look like to generate the two profiles. Hopefully this is enough for you to get started?

![1stversion_twoprofiletypes](https://cloud.githubusercontent.com/assets/14365107/11651281/8cb7eb02-9d44-11e5-99d0-bae4ffd362c2.jpg)

**Comment by samuelreh** [comment]
I started this but am still waiting for the planning to be finished right?

**Comment by jonaspiet** [comment]
yes.
@Sam: sorry we had a delay on our end but will get this done this week.

jonas.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by lisajoytrick** [comment]
hey Sam, 

As per our conversation monday we're ready to open this up again to work on, although I think the feature hasn't been fully scoped out. 

I understand you have already built a portion of it including
1. the functionality for someone to choose the host or kudoer profile 
2. have that direct them to a different profile template
3. Admin to create "person's fields" specific to the various profiles (see screenshot below for how I imagine this might look?)

<img width="1142" alt="screen shot 2016-01-21 at 3 31 43 pm" src="https://cloud.githubusercontent.com/assets/14365107/12498058/8e7220f6-c054-11e5-86d2-4344b8fcb942.png">

For the next version:

- there should be a way for admin (and/or users) to choose to have both profile types associated with their account (see example below)

![kudoerhostprofile](https://cloud.githubusercontent.com/assets/14365107/12498138/3169db82-c055-11e5-9575-8d1acd12d39d.jpg)
