### ISSUE TITLE
Badges Feedback

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#21]
1. can the menu on the main page be adjusted?
from All listing types > to Badges & Experiences
pluralize Experiences & Badges + switch order (badges first) if it’s easy to do 

2. admin menu with "edit listin" option isn’t available on badge listing types (screenshot #1)

3. thumbnail image sizing issue re: experiences for some window sizes (screenshoot #2) and it would be nice if the complete description text didn't display but rather a read more link after a certain character or word count.

4. only admin user type can create badges…
 so from https://kudoz-staging.herokuapp.com/en/listings/new# we need the option to choose either type to be disabled for regular users

<img width="2115" alt="screenshot1" src="https://cloud.githubusercontent.com/assets/14365107/11042040/f8bb25ee-86e2-11e5-88c1-4b078abced12.png">
<img width="1197" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/14365107/11042041/f8bdc7d6-86e2-11e5-8f0b-918e9bfa464f.png">

**Comment by samuelreh** [comment]
These are all done :)
