### ISSUE TITLE
Availability calendar 

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#22]
To illustrate some issues we’re having with the sharetribe availability calendar I’ve filmed a short screen recording: https://www.youtube.com/watch?v=WpAKk81-CTc

1. 0:03 & 0:12 from the week view (default view) when you create a reoccurring event it doesn’t show up right away but when I switch to month view. 0:15 I can see the event I created so it is actually happening

2. Also, I think that when you make a reoccurring event at a PM time it changes to AM. (i.e.: 0:43) It’s a bit hard to see if this is happening since reoccurring events don’t show up immediately but when I look at the month view I an 7 AM event although I tried to make it at 7 PM

**Comment by lisajoytrick** [comment]
Actually after some more testing I've realized that both problems are the same (ie #2). It looks like no reoccurring event is being created but it actually is being created it's just so early that you don't see it in the week view easily without scrolling

**Comment by samuelreh** [comment]
Nice find! It's fixed now. :smile:
