### ISSUE TITLE
enabling markup in badge description

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#23]
Can you enable simple html markup in the badge description field? After that I think the badge feature is ready to roll over into production. Yahoo!

<img width="1062" alt="screen shot 2015-11-12 at 10 45 46 am" src="https://cloud.githubusercontent.com/assets/14365107/11127889/67757634-892b-11e5-8547-92ca2d854d0c.png">

**Comment by samuelreh** [comment]
<img width="1037" alt="screen shot 2015-11-12 at 12 03 53 pm" src="https://cloud.githubusercontent.com/assets/128012/11129660/7fef532e-8935-11e5-9c74-48a7841b0638.png">
