### ISSUE TITLE
Re-order & re-categorize listings

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#26]
From "admin" > "view listing" it would be great if we could re-order & re-categorize a listing. 

Since the order is sorted by date listing is published, I think the easiest way to do this would be to be able to edit the date posting is published. 

Not sure about reassigning categories, maybe you have some ideas of how we could do that?

<img width="902" alt="screen shot 2015-11-13 at 3 39 16 pm" src="https://cloud.githubusercontent.com/assets/14365107/11160326/3a525a1c-8a1d-11e5-9dcf-8f2abbb3fe8d.png">

**Comment by samuelreh** [comment]
- Add input for changing of sort date on admin listing edit page (0.5 hr)
- Allow changing of sort date in admin listing controller (0.5 hr)

**Comment by lisajoytrick** [comment]
approved - please proceed
