### ISSUE TITLE
reseting/changing a user's email 

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#27]
We have some users who's email addresses have changed + they've forgotten their password. 

From the admin role we are not able to update a users email address and they can't access their link to reset themselves.

**Comment by lisajoytrick** [comment]
Andie has run into hosts who signed themselves up (not the ones we created email addresses for) who have changed email accounts or unsure which email account they used. They've tried the password retrieval but haven't received a reset link at their current email. 

Regardless, I think exposing email addresses to admin will be necessary when we get to the circle onboarding anyways.

**Comment by jonaspiet** [comment]
ok. So:

As an admin, I am able to see, add and change all email addresses related
to an account.

Do we want all email addresses to be confirmed?







*Jonas Piet*

*Partner and Lead Service Designer InWithForward*
MOBILE 778 232 8214
SKYPE jonaspiet

**Comment by lisajoytrick** [comment]
Yes, Jonas your right. The request is that 
> Admin can edit/add email addresses associated with an account. Ideally it doesn't need to be confirmed but if there is no way around that step I'm sure we can sort that out.

**Comment by samuelreh** [comment]
Estimate: 1 hr

**Comment by lisajoytrick** [comment]
1 hr estimate approved.

**Comment by samuelreh** [comment]
Admins can now edit user profiles the same way users can edit their own profiles.
