### ISSUE TITLE
sign up via facebook- not working

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#3]
I tried setting it facebook login and sharetribe but it's not working completely. It looks like it is at first but doesn't completely enroll a new user. See error message:

<img width="1054" alt="kudoz_facebook error" src="https://cloud.githubusercontent.com/assets/14365107/10924951/49f97760-823f-11e5-9955-d5af959752ff.png">
<img width="1034" alt="kudoz_facebook error 2" src="https://cloud.githubusercontent.com/assets/14365107/10924952/49fa7f84-823f-11e5-981a-00aa32f2d271.png">

**Comment by lisajoytrick** [comment]
I've removed the app secret & id for now so that the button won't display for users until we can get it working.

**Comment by samuelreh** [comment]
This should be fixed, can you give it another shot.
