### ISSUE TITLE
Resetting password causing error message

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#31]
A user tried to reset their password using the email address associated with their account (or at least what they remember associated with their account.) This message occurred:

![pasted image at 2015_11_23 10_06 am](https://cloud.githubusercontent.com/assets/14365107/11346725/d3410f90-91d2-11e5-97d0-56662cb46aad.png)

**Comment by samuelreh** [comment]
The error on the backend reads: "Postmark::InvalidMessageError: You tried to send to a recipient that has been marked as inactive. Found inactive addresses: moniquekudoz@gmail.com. Inactive recipients are ones that have generated a hard bounce or a spam complaint."

**Comment by lisajoytrick** [comment]
ok... so what can we do in this situation to get the user up and running again?

**Comment by samuelreh** [comment]
Are you 100% sure this email address exists? The postmark docs say: "Hard Bounce: The email address no longer exists."

**Comment by lisajoytrick** [comment]
hum... let me look into it

**Comment by lisajoytrick** [comment]
Yep - it's a real email address and I'm able to login and check it but there are no messages from kudoz. (I've check spam and trash)

**Comment by samuelreh** [comment]
I reactivated the address in Postmark. 

It looks like the confirmation email bounced on April 4th, and so the address was marked as invalid:

"smtp;550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at http://support.google.com/mail/bin/answer.py?answer=6596 c77si9141255ioc.41 - gsmtp"

It it possible the person signed up before the email address existed?

**Comment by samuelreh** [comment]
If this happens again, you can go to Heroku => kudoz-production => Postmark (under add-ons).

Once in the Postmark app, you can click 'Activity' and then filter by 'Inactive Emails'. 

These are emails that have been de activated due to a delivery error. They can be re activated here.
