### ISSUE TITLE
Reminders for listings with no availablity

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#32]
We are finding that our hosts are just putting in 1-2 dates (or none!) in their availability calendar and when the dates past, they are forgetting to log back in and add more availability. 

We would like to try prompting them and are wondering which of these mechanisms would be easiest/feasible to build:

*our preferred method* > (1) system sends them an SMS or email (depending on which preference they have chosen in their person's field "which do you prefer?") when they have less then three (1 or 2) upcoming available time slots

*alternative option*(2) system sends them and hello@kudoz.ca an email when they have less then three (1 or 2)  upcoming available time slots. We follow up manually if we think it might not be reaching them

To avoid being super annoying I think the reminder should be triggered every 5 days.

Let me know which of these options looks doable and I will develop copy.

**Comment by samuelreh** [comment]
I'd say the second option is less work. 

It's actually easier to run reminders on specific days of the week or dates, if that's fine, either the 1,5,10,15,20,25 of every month or every maybe Monday?

Here's an estimate (2.5 hr):
- Scheduled Job - 0.5 hrs
- Logic for querying listings with few availabilities - 1 hr
- Email to user: 0.5 hrs
- Email to admin: 0.5 hrs

**Comment by lisajoytrick** [comment]
ok great  - estimate looks good and we're working on copy

**Comment by samuelreh** [comment]
Did you ever finish the copy for these emails? I can finish this task off
if so.

**Comment by samuelreh** [comment]
Did you finish the copy for this? I can finish off the task if so.

**Comment by lisajoytrick** [comment]
Thanks for the reminder. Here's the copy:
https://docs.google.com/document/d/1VHJTqyTrUcXne4FH7rqImjfiW7bIdsJaBjWEC-fxVYk/edit?usp=sharing

On Tue, Dec 1, 2015 at 10:28 AM, Samuel Reh <notifications@github.com>
wrote:

> Did you finish the copy for this? I can finish off the task if so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/InWithForward/sharetribe/issues/32#issuecomment-161055418>
> .
>



-- 

Lisa Joy Trick

Interaction Designer, InWithForward

MOBILE 778 809 2780

SKYPE lisajoytrick
TWITTER @lisajoytrick

**Comment by samuelreh** [comment]
Unfortunately I can't do the copy rotation thing without adjusting the estimate. It would tack on another hour. If you think it's worth it, I can proceed, but if not, which one of those three do you want to use?

**Comment by lisajoytrick** [comment]
hum, ok. we're going to test this manually first so lets hold on this till I get back to you with more info about what seems to be working for users.

**Comment by samuelreh** [comment]
This is done and I can set up a task to run it on prod on (every 5 days) 1, 6, 11, 16, 21, 26.

What time do you want the reminders sent at?

**Comment by lisajoytrick** [comment]
Sorry Sam - a bit of confusion here. I wanted to hold off on this feature for now because we're testing sending these reminders out manually to see how people feel about them. We don't want to annoy our users by spamming them and we've realized that there are some hosts who are only interested in hosting every couple months who would be bothered by these. I expect we'll end up revising the feature to only run a couple times a month.

**Comment by jonaspiet** [comment]
I am hoping that feature #81 (task 5), will encourage hosts to make a recurring booking. Which I'm hoping will become more common behaviour.

**Comment by samuelreh** [comment]
ok, so this will go out tomorrow at 10AM

**Comment by jonaspiet** [comment]
:)


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by jonaspiet** [comment]
I am afraid hosts don't get the regular reminders to add dated to their calendar if they have a limited number of available slots. I can't find any trace of the reminders on Postmark and @AndieFro hasn't heard from hosts about them...

@samuelreh could you check if this feature is working well? Thanks!

**Comment by samuelreh** [comment]
Yep, you're right. this was broken. Should be fixed now though. Should send out next tuesday.

**Comment by jonaspiet** [comment]
Thanks! next Tuesday 10am, as in the 23rd Feb, right?
and then bi-weekly?

**Comment by samuelreh** [comment]
yep!

**Comment by jonaspiet** [comment]
andie / 23 Feb
8:33 PM Hey Jonas. Our email has worked a little too well... I've had 2 phonecalls and an email from hosts thinking Zach and Jordana are literally trying to book their experiences and are now waiting to hear back from them haha. We'll need to adjust the text a little more before the next email goes out.
