### ISSUE TITLE
add privacy policy confirmation on signup

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#40]
When someone creates a new account there is a check box to accept terms of use. Can there be two check boxes?
[  ]  I accept the terms of use
[  ]  I accept the privacy policy

<img width="1143" alt="screen shot 2015-12-08v2" src="https://cloud.githubusercontent.com/assets/14365107/11650735/7b5b92e0-9d40-11e5-9d99-332c23936e45.png">

**Comment by samuelreh** [comment]
They're both required right? Might it be easier for the user if they could just check one box that says:

  [ ] I accept the terms of user and privacy policy

**Comment by lisajoytrick** [comment]
yep. They can be one line as long as the text links to the two separate pages.
