### ISSUE TITLE
upload mp4 files (required for new user types profile)

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#42]
To make it easier for a user to create a video and share it on their profile, we want to reduce the steps of uploading to youtube and generating the share link.

Can there be functionality to upload a mp4 file and play it on the front end in the same way that a user can currently upload a jpg or png as a profile photo?

![screenshot_2015-12-07-13-15-53](https://cloud.githubusercontent.com/assets/14365107/11667723/40d85528-9da8-11e5-91e0-6d53ba440f2d.png)

**Comment by samuelreh** [comment]
Uploading video is very trivial. If I were you I would wait on this feature. I would estimate it, but I wouldn't be surprised if the estimate lands anywhere from 6 - 12 hours of work. I'm not sure how important this is to you. If you want me to proceed with the estimate though, I will.

**Comment by lisajoytrick** [comment]
Ok, I will see what other ideas I can come up with. We're finding that asking a user to film their video, then upload it on youtube,  then share the link is to many steps ... but maybe there's another solution?

**Comment by jonaspiet** [comment]
Hey Lisa, are you concerned about hosts, or kudoers, or both? At which
points in the process does this happen?
I am not sure if the best solution is for people to upload videos to our
database.

With the *host,* maybe we can upload their video after the host induction
(H.03)? Or make the host induction a little longer and get hosts to do it
themselves?
It's a nice and personal part of the induction?

With *Kudoers*, isn't this part of the kudoer profile making (K05-K.06)? In
this experience there's one of us, and there's some time, right?

@Sam: should we also be conscious of the amount of data stored and played
from  our database / server and the costs and speed related to that?

thanks!
jonas.



*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
@jonaspiet storage would be on Amazon S3. Although it's fairly cheap, video uploads can add up.

**Comment by lisajoytrick** [comment]
@jonaspiet this feature request comes from the learning Gurus so they are concerned with making things as easy as possible with the Kudoers. 

I think that the profile making kit is left behind with the circle so the ability to add media to the kudoer's profile & dashboard needs to be a interaction that is user-friendly enough for them to do on their own at their home and without our in person assistance.

**Comment by jonaspiet** [comment]
we want to  will be auto uploaded / embedded 
to be replaced with feature #70
