### ISSUE TITLE
Requiring fields to be completed before messaging/requesting is allowed?

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#43]
Hey Sam,

We have users who are creating a basic account with no profile data and then booking through the messaging system because they are not yet marked with "allowed to request." Can we create an "allowed to message" column on the admin level that defaults to no until we've allowed them?

Can we also have a message like this that displays if they try to message or request? We like how this message prompts the user to fill in more information about themselves so we can better understand who they are. If it's possible I could let you know what required fields we would like filled out before requesting/messaging is allowed.

<img width="1209" alt="screen shot 2015-12-17 at 1 30 42 pm" src="https://cloud.githubusercontent.com/assets/14365107/11882705/ea41e964-a4c2-11e5-864b-6fb9e8659dcb.png">

**Comment by jonaspiet** [comment]
do we want to make *one* tick box that says 'allowed to request and
message"?

this is basically later to be replaced by the credits / subscription system
we'll need to develop




*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
@jonaspiet I think that would be a bit simpler. I can't think of a use case that you would want to check one and not the other.

**Comment by samuelreh** [comment]
I implemented it so if you can't request a listing, you can't create messages to users as well. This functionality is on production now. Good enough for now right?
