### ISSUE TITLE
48 hour reminder email - timing question

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#44]
It seems that currently the "48 hour reminder email" is being sent out at the time an experience is booked rather then 48 hours before the experience time. Can you check on this and make sure it's going at the 48 hour mark?

ie: subject: "Reminder - you’re hosting a Kudoz experience on - November 20, 2015, 02:30 PM"

**Comment by lisajoytrick** [comment]
Additional questions/suggestions:

Please confirm that the 48 hour reminder email is sent to both the host and the kudoer/requester? Is the subject line customized per user type? Ie: "you're hosting..." "you're going on...?"

Is there is also an email that arrives when a booking is confirmed for the requester? Can we have an email at the time a time slot is confirmed that is received by the requester & the host with all the content from the 48 hour reminder email but the subject line of the email is "Confirmed: {experience title} {date} {time}"

**Comment by samuelreh** [comment]
Nice find, it was sending it out immediately (which we want on staging for testing but not on production). I fixed it to be 48 hours before the booking.

Yes the subject lines are different depending on the host or requester. Right now they are:
      subject: "Reminder - you’re hosting a Kudoz experience on - %{date}, %{time}"
and:
      subject: "Reminder - Kudoz experience coming up - %{date}, %{time}"

Right now, the requester gets this 48 hours before and immediately. The host only get's it 48 hours before. You want them both to receive a confirmation immediately. With the new subject line: "Confirmed: {experience title} {date} {time}"?

**Comment by lisajoytrick** [comment]
Yep: can they both get it immediately with the new subject line "confirmed..."
+ can they both get it 48 hours before with the subject line "reminder..."

thanks!
