### ISSUE TITLE
48 hour reminder email - add content

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#45]
Please add the content from Listing Fields > "Location details & meeting up"  to the 48 hour reminder email and confirmation email

**Comment by samuelreh** [comment]
I assume this should be in the email to the requester. Should I add it to the email to the host as well?

**Comment by lisajoytrick** [comment]
For sure for the requester. For the email to the host the pretext could read: 

"here's what the Kudoer who requested your experience knows about how to find you" Please message them if there's anything additional you'd like them to know" {insert details}
