### ISSUE TITLE
Deleting one event on a repeating availability 

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#46]
Currently we have a number of users requesting to be able to remove a one instance of a recurring event. This is important because sometimes a user has completed two availabilities for a day of the week (ie: tues 1-2:30 and 3-4:30) but they are away for a week so not available one particular tuesday. Kudoers keep requesting those two time slots and the host has to reply "neither" to the request. The host is prompted to update their calendar but they can only remove those time slots by deleting the reoccurring event all together. Then they may not create a new availability for future tuesdays. Also, if the tuesday they are not available is a month or two away, they can only create a new timeslot for after that particular week they are away.

**Comment by samuelreh** [comment]
This is actually more of an enhancement than a bug. And unfortunately It'll take a little effort to implement. I can do it but I'll have to bill for it as a feature (probably a couple hours). Would you like me to estimate it?

**Comment by lisajoytrick** [comment]
Sorry for the incorrect category. Thanks for fixing. Please estimate.

**Comment by samuelreh** [comment]
2.5 hrs:
- Add UI modal for choosing to remove single instance or all instances (1 hr)
- Creating an event for every week (for the next 3 years?) (1 hr)
- Deleting every instance JS logic (0.5 hr)

**Comment by lisajoytrick** [comment]
approved. please proceed.
