### ISSUE TITLE
network awareness message

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#47]
Sometimes our users are filling out their profile or experience listing fields and they get disconnected from the internet. They don't realize this and go to save their content and lose it. To reduce the likelihood of this happening I would like to increase their network awareness and prompt them to reconnect before saving/proceeding. 

Request:
When a user is logged in and their internet connection is lost could a message display along the top of their browser to indicate a lost connection? See example. 

<img width="1233" alt="screen shot 2015-12-21 at 10 12 10 am" src="https://cloud.githubusercontent.com/assets/14365107/12059015/35a60fda-af08-11e5-9960-b4f898d14772.png">

**Comment by samuelreh** [comment]
2 hrs:
 - 1 hr: js logic & testing
 - 1 hr: status endpoint

**Comment by lisajoytrick** [comment]
approved. please proceed.
