### ISSUE TITLE
experience listing "loosing" category

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#48]
I just edited this listing: https://catalogue.kudoz.ca/en/listings/33-walk-and-train-mischa-the-dog

I added a word to the keywords field. Now it no longer displays in the category it was previously displaying in (ie: Animal Hobbies)

I replicated the issue with my own experience (pizza on the BBQ.) I edited a field and added a keyword to that text field and now it's gone from the food section but I can still see it on the home page.

**Comment by samuelreh** [comment]
The catalogue page re indexes every 10 minutes (on the ninth minute: 1:09, 1:19, 1:29...). So after you change one of the indexed fields, you'll probably have to wait until after it runs.

If this is a big problem. I could look into changing it so it updates after any listing changes. Might not be too hard.
