### ISSUE TITLE
Highrise cc-ed in messages

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#50]
I've created a Highrise account for our Kudoz catalogue and I was wondering if we can set Sharetribe to Bcc all messages to users to this email address: dropbox@32261300.kudoz.highrisehq.com. Then, we can see a history of messaging in our Highrise contact manager.

**Comment by lisajoytrick** [comment]
Anything else you need from me to quote on this feature?

**Comment by samuelreh** [comment]
This should work now. Let me know if you're not seeing new emails in highrise.

**Comment by lisajoytrick** [comment]
hum. It bounced but I think this might be a highrise issue. I'll email highrise.
