### ISSUE TITLE
redirecting user at email address confirmation point

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#51]
Upon signing up for a Kudoz catalogue account a user gets a message to confirm their email address. 

Can the webpage that the user is directed to upon confirming the email address be the "edit profile" page? https://catalogue.kudoz.ca/en/username/settings/profile

Currently they end up on the catalogue homepage. We're hoping to increase the chance that the user fills out these profile fields.

**Comment by samuelreh** [comment]
- changing and testing: 0.5 hr

**Comment by lisajoytrick** [comment]
Fantastic! Tested and working :)
