### ISSUE TITLE
phone number exchange feature

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#52]
Sam, can you quote this feature?

We would like to give the hosts & kudoers a chance to exchange phone numbers before an experience to help them communicate and connect in-person. 

Could we add a button to the 48 hour reminder email for both parties that reads 
“Are you comfortable sharing your cell phone number with this person? It’s helpful to have each other's numbers when meeting up.”   button text: YES

If they press YES, systems look up their primary number from their user profile. If the field is empty they are prompted to fill it out. If it’s complete, the system sends their phone number to the other party via SMS AND email message.

Text:
Fellow Kudoz member, {kudoz username}, has shared their phone # with you {phone number}. Don’t forget to add to your contacts!

**Comment by samuelreh** [comment]
- 48 hour reminder text & button (0.5 hr)
- View and action for if they haven't entered their phone number yet 1.5 hr
- action and job for sending notifications (SMS and email) 1 hr

**Comment by lisajoytrick** [comment]
approved. please proceed.

**Comment by samuelreh** [comment]
@lisajoytrick I'm a little confused at where you want the text and button in the reminder email.

Also, should this text and button go in the immediate confirmation email as well?

**Comment by lisajoytrick** [comment]
re: immediate confirmation email: yes! That would be great. 

Re: location/look - see screenshot
<img width="683" alt="screen shot 2016-01-11 at 2 04 48 pm" src="https://cloud.githubusercontent.com/assets/14365107/12248372/cfe3b7be-b86d-11e5-8a07-2632c45bc903.png">

**Comment by samuelreh** [comment]
This is done and on production.

**Comment by jonaspiet** [comment]
Hey Lisa, sorry this slipped through as I was away when the first emails
were send.
I know it's already build and we've spend 2.5 hours on it. But I think the
system works better without?

Can't we let with hosts (on signup) that their number is shared with a
Kudoer whenever they confirm the experience? And the other way around?

This makes it one more click to get things done... One more thing that can
hold up the booking process.

Can we roll it back? What is your opinon?

Jonas.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
We could roll it back...

I think the point of doing it this way was because hosts might want to interact with the booking system via SMS but not necessarily the share it with the Kodoers. This way also gives them to freedom to share it with some Kodoers, but not necessarily all of them.

However, you bring up a good point, it does introduce another step in the process. Maybe the complexity is not worth the control.

**Comment by jonaspiet** [comment]
@samuelreh

**Comment by samuelreh** [comment]
@jonaspiet what do you mean by the 48 hr reminder text message? I don't think we have a 48 hr txt message reminder, just email. Maybe I'm forgetting something though.
