### ISSUE TITLE
host "reminder to repsond" - message problem

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#56]
As a host, I haven't yet replied to a request for my experience so I got a reminder email. 
<img width="500" alt="screen shot 2016-01-05 at 9 13 19 pm" src="https://cloud.githubusercontent.com/assets/14365107/12135478/339cb0ac-b3f1-11e5-9655-c6a235aed97e.png">

I clicked "show details" and got a not allowed to see content message:
<img width="500" alt="screen shot 2016-01-05 at 9 14 30 pm" src="https://cloud.githubusercontent.com/assets/14365107/12135503/7be90504-b3f1-11e5-8a7a-72e754c2dd6a.png">

I can actually see the content if I go into my Inbox though, so I expect there's a problem with the url for the "show details" button maybe?
<img width="500" alt="screen shot 2016-01-05 at 9 14 38 pm" src="https://cloud.githubusercontent.com/assets/14365107/12135512/92e49aac-b3f1-11e5-9ea3-1412be29284c.png">

**Comment by samuelreh** [comment]
nice find. this has been fixed and deployed
