### ISSUE TITLE
admin user sending another user a message

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#57]
As an admin, I wan to be able to send a message through the catalogue, to any user, from their profile page. Including users who don't have an experience listing, i.e. Kudoers. 

Right now, regular users CAN do this.
Admins can ONLY message users through their experience listing.

On a profile, regular user sees:
<img width="500" alt="screen shot 2016-01-06 at 3 50 44 pm" src="https://cloud.githubusercontent.com/assets/14365107/12158385/5bb1c88c-b48e-11e5-8625-fae0bcad05cc.png">

Admin user sees:
<img width="500" alt="screen shot 2016-01-06 at 3 55 41 pm" src="https://cloud.githubusercontent.com/assets/14365107/12158387/5e9b4e6a-b48e-11e5-98f7-f29a3a03268d.png">

**Comment by lisajoytrick** [comment]
@jonaspiet I'm bumping this up from wishlist to needs estimation as our learning gurus would really like to be able to send messages to kudoers through the platform rather then via email so the kudoers can have their messaging centralized.

**Comment by samuelreh** [comment]
@AndieFro this should work now.
