### ISSUE TITLE
Changing categories over time: data To Mixpanel

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe#59]
Report types of categories users are choosing, per user breakdown

Metric:
Meaningful Employment / more interests / exploring something different?

**Comment by samuelreh** [comment]
This should be queryable from the event triggered when a kudoer books an experience. We'll associate a category with the experience so we can break it down.

**Comment by jonaspiet** [comment]
Great, let's do it!


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet
