### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe#62]
Allow users choose components to make up a sentence, using a time frame, an action, and an outcome.

For example: "This winter, I want to learn some Japanese, so that I can write my name." 
OR "This winter, I want to try learning three new languages, so I can find one I'd like to study more." 
This would be a highly specific goal Versus "this year, I want to get a job."

@samuelreh : if you have a different idea on how to build this - I'm interested!
![screen shot 2016-01-28 at 4 32 38 pm](https://cloud.githubusercontent.com/assets/11308069/12648990/d92f816e-c5dc-11e5-8e43-ab39420b8f85.png)

Metrics:
Meaningful Employment / Goal setting / How specific are goals?

**Comment by jonaspiet** [comment]
![screen shot 2016-01-19 at 6 16 36 pm](https://cloud.githubusercontent.com/assets/11308069/12438172/e3f71090-bed8-11e5-9c91-dc8d4455b439.png)

**Comment by samuelreh** [comment]
@jonaspiet 
- Add new customer field type 1 hr
- Create new learning goal form 1 hr

What options do you want in the second drop down? :
- Try
- Learn
- Visit
- Build
- Practice

**Comment by jonaspiet** [comment]
@samuelreh i changed wording for both elements slightly. Looking forward!

this week
this month
this summer
this winter
this year


Try
Learn
Improve
Build
Practice

**Comment by samuelreh** [comment]
@jonaspiet this is on prod now. You can add a new custom field called "Goal". Let me know if you need to change the placeholder copy at all.

**Comment by jonaspiet** [comment]
@samuelreh this works well for now.

question: how much time would it take (roughly) to make a feature like this editable within the 'profile view' page (i.e. not switching to the entire 'edit profile' page)?
