### ISSUE TITLE
Profile Endorsment

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe#64]
Measure profile updates in mixpanel

Simple:
- Feedback from host (description of Kudoer). Send this to kudoer an email with feedback

More complicated / better UI options:
- Display feedback from host (description of Kudoer) in the kudoer's profile, near the 'about me' section.
- Endorsements from host at feedback screen, Freeform text.

Metric:
Positive mental health / Self awareness / How does a Kudoer describe themselves?

**Comment by samuelreh** [comment]
- Change display of reviews on profile page (change wording, get rid of positive or negative) 0.25
- Show rejected and accepted for admin 0.25
- Change feedback received email to include accept or reject buttons 1
- Add actions for accepting and rejecting feedback 0.5
- Add status field to feedback model (pending, accepted, rejected) 0.5
- Change display of feedback form (change wording, remove positive and negative) 0.25

Total: 2.75

**Comment by jonaspiet** [comment]
Build on existing 'review' functionality
> take out positive / negative
> shuffle wording in displayed field: [host user] about [listing title] experience, [time passed] ago. 
> hosts endorse Kudoers and vice versa
> user chooses in email to 'add to my profile' or 'don't add to my profile'
> admins can see accepted, rejected and pending endoresements on a user's profile

Wording in review prompt message:
"You've just done the [listing title] experience with [user].
In the spirit of Kudoz, can you write a few words of feedback to [user]?"

Title on profile box:
"What other people say about me"

![screen shot 2016-02-16 at 7 59 19 pm](https://cloud.githubusercontent.com/assets/11308069/13087681/7130c8d6-d4e9-11e5-9668-14baf7b65b00.png)

**Comment by jonaspiet** [comment]
please proceed! 
looking forward to see this one

**Comment by samuelreh** [comment]
@jonaspiet 
Which parts of this do you want to change if any?:
<img width="677" alt="screen shot 2016-02-16 at 1 18 36 pm" src="https://cloud.githubusercontent.com/assets/128012/13091407/dca0711e-d4af-11e5-869d-1ef8704fe68c.png">

**Comment by samuelreh** [comment]
This feature is on production now. I didn't update the text of the screenshot above though.

**Comment by jonaspiet** [comment]
Endorse [user name]!

This endorsement will be visible to others on [user’s] profile. [User] can accept or reject your feedback − in this way [user] and others get to see new sides of themselves!

What do you want to share with [user]?  
What did [user] say or do that you noticed? 
(Please write one or two sentences)

[Send endorsement]

**Comment by jonaspiet** [comment]
Endorse [user name]!

This endorsement will be visible to others on [user’s] profile. [User] can accept or reject your feedback − in this way [user] and others get to see new sides of themselves!

What do you want to share with [user]?  
What did [user] say or do that you noticed? 
(Please write one or two sentences)

[Send endorsement]


![Uploading Screen Shot 2016-02-17 at 1.04.14 PM.png…]()
