### ISSUE TITLE
CSV export of experience transaction data

### ISSUE THREAD

**Issue by samuelreh** [InWithForward/sharetribe#67]
Build a CSV export of the transactions list.
(Related to engagement metrics)

Metrics:
Reciprocity / Fluid Roles / Track # of Kudoers who take up taster,  transitologist or host role

**Comment by samuelreh** [comment]
Add csv export button 0.25 hr
Add action 0.25 hr
Add service for exporting 1.5 hr

**Comment by jonaspiet** [comment]
Great, let's do it!


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by lisajoytrick** [comment]
Hey Sam, Do you think this feature will be available for us within the next week or two?

**Comment by samuelreh** [comment]
Yes, this should be possible.

**Comment by lisajoytrick** [comment]
awesome!

**Comment by lisajoytrick** [comment]
@samuelreh how big of a deal is it to extend this feature to other content types? Could it be available on "view listings" and "manage users"?

**Comment by samuelreh** [comment]
Not a huge deal. I'd estimate an 45 min for each. 1.5 hr total.

**Comment by lisajoytrick** [comment]
ok. Let's proceed with putting it on the listings page and wait on the user page since we might pull this out of mixpanel in the future.

**Comment by jonaspiet** [comment]
@samuelreh : could you build the CSV export for the listings page please?

**Comment by samuelreh** [comment]
@jonaspiet @lisajoytrick I added a CSV export for listings. Right now the column are the same as the displayed columns in the admin section. However, I can add additional columns if you think of anything that would be useful here.

**Comment by jonaspiet** [comment]
@samuelreh This is very useful.

two questions:
- can you split 'Crim check', 'Safety check', and 'Taster' in seperate fields? so we can easily sort and filter hosts in a spreadsheet accordingly.
- can you also export available fields in their calendar? if it's recurring maybe it can be listed as such, instead of an infinite list...

**Comment by samuelreh** [comment]
@jonaspiet How would you like to see the availabilities? What's the use case we're trying to solve?

**Comment by jonaspiet** [comment]
i think tha tthe aggregated calendar / filter function we discussed today
is making this feature obsolete!


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet
