### ISSUE TITLE
calendar event update not reflected on request page

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#71]
I noticed a listing with a reoccurring 3:30 AM availability slot so I updated it to be at 3:30 PM.

<img width="1095" alt="screen shot 2016-01-19 at 10 46 43 am" src="https://cloud.githubusercontent.com/assets/14365107/12428631/9407c9e6-be9a-11e5-96ef-fcd1c7513a48.png">

When I requested the experience I still see the AM time slots but I have gone back to double check the listing and it's showing PM time slots. Is there a significant delay from when the events are updated and when they display as updated on the request page?

<img width="1100" alt="screen shot 2016-01-19 at 10 47 18 am" src="https://cloud.githubusercontent.com/assets/14365107/12428695/0bd7c818-be9b-11e5-9613-824a021d9fa0.png">

**Comment by samuelreh** [comment]
The ones you added don't seem to be recurring. Were they meant to be?

The AM ones were only deleted for the current week, they seem to still be there in the future. However, i just deleted the AM ones to make sure it was working.

I added the PM slots as recurring. Seems fine to me.
