### ISSUE TITLE
Automatically create Trello card when booking an experience with support 

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe#73]
When a user books an experience and ticks the bo 'travel support needed', a Trello card is created automatically on the list "Journeys posted". This card includes the following [sharetribe fields]:
> [pick-up address] would be a new profile field 

- Title: [Kudoer pickup address] > [experience location]
- Due date: "arrival at experience" [experience time] + [day]
- Attachment: URL to experience listing

- Description:
[kudoer name]
[phone number]

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
nice to have's:

- Checklist:
[  ] calculated route
[  ] texted kudoer one hour before
[  ] brought back kudoer and moved to 'job done'

- Labels 
pickup location (Burnaby, Coquitlam, Vancouver, New West)
experience location (Burnaby, Coquitlam, Vancouver, New West)

![screen shot 2016-01-19 at 6 55 02 pm](https://cloud.githubusercontent.com/assets/11308069/12438714/30643fe8-bede-11e5-8b53-f67ae745268a.png)

**Comment by samuelreh** [comment]
Hard code in Trello Auth: 0.5 hr
Create Card: 1.5 hr

**Comment by jonaspiet** [comment]
Great, let's do it!


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
@jonaspiet can you invite me to your Trello board (as an admin)? my trello handle is @samuelreh1

**Comment by lisajoytrick** [comment]
me too. @lisajoytrick1  - also, can we make sure the board is set up as a "team board" with privacy settings for the team and we can add transitologists to the team?

**Comment by lisajoytrick** [comment]
Also, at the point in sharetribe where a user is being asked if travel support is needed, can we also display the [experience location] so they have that information available when trying to decide?

**Comment by jonaspiet** [comment]
i added you as a member.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
Can you actually invite @kudozapi as well. This will be the user that automatically creates cards.

**Comment by samuelreh** [comment]
Where should the 'travel request needed' box go? In the original estimate I was assuming that box was part of the user profile or something... I'll need to increase the estimate to add this detail.

**Comment by lisajoytrick** [comment]
Hey Sam, 

I think ideally the user would say whether they need travel support or not at the point of booking the experience because it may or may not be out of their comfort zone but for an MVP version of this feature we could just build it as a person's field

field question:
Do you need us to arrange a support person to help you travel to & from experiences? This means help taking the bus or skytrain. 
[ no ]
[ yes ]

Might it make sense to bump up issue #20 first so we can put this question under the kudoer profile specifically?

**Comment by samuelreh** [comment]
Is this in addition to some sort of field that specifies where they should be picked up?

**Comment by jonaspiet** [comment]
Sam, thanks for building this. I invited @kudozapi - could you confirm them
as trello member? I don't know which email address is related to that
username.


thanks!



*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
I've confirmed that email address. It's currently samuelreh+kudoz@gmail.com. I can transfer it to a different address if you'd like.
