### ISSUE TITLE
Adjusting the message received by a host when a booking request is made

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#75]
When a kudoer requests an experience the SMS message is received by the host with the two timeslots. This works well. 

But, another message is received (via email) that is very generic and I'm wondering if it can be more specific. Maybe the subject line could be {kudoer's username} has requested {experience title} - please confirm a time that works for you. If you have already confirmed a time via SMS, you can ignore this message.

Button could read "See Request Details"

<img width="1088" alt="screen shot 2016-01-26 at 9 44 50 am" src="https://cloud.githubusercontent.com/assets/14365107/12589426/7f3de75c-c412-11e5-9fc4-325e4e2956c5.png">

**Comment by samuelreh** [comment]
Haha, the sharetribe authors agree with you. From the codebase:
# TODO Now that we have splitted "new message", we could be more specific here, and say that this message is about a new transaction!

**Comment by lisajoytrick** [comment]
who are these mysterious sharetribe authors?

**Comment by samuelreh** [comment]
https://github.com/rap1ds is the one in this case :)
