### ISSUE TITLE
old badges on kudoer user profile

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#76]
I helped a new kudoer create an account today and it already has "badges" loaded into it. 

Is it possible that there is  a bit of glitch and the user role is attached to some old badge content. Clicking through to these "badges" generates errors.

<img width="1133" alt="screen shot 2016-01-26 at 2 13 23 pm" src="https://cloud.githubusercontent.com/assets/14365107/12598684/9cb0f1fc-c440-11e5-99e3-865b18e74190.png">

**Comment by samuelreh** [comment]
Good catch. Should be good now.
