### ISSUE TITLE
Admin marking experience as cancelled

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#77]
It's working well for admin to mark experiences as completed but sometimes an experience doesn't happen. Can there be an option to mark as cancelled? 

<img width="1107" alt="screen shot 2016-01-26 at 4 13 38 pm" src="https://cloud.githubusercontent.com/assets/14365107/12599641/8ef0047e-c448-11e5-9cf9-7ba712ff99c3.png">

**Comment by jonaspiet** [comment]
taking out 'high priority' i think we wait with this for now

**Comment by jonaspiet** [comment]
@samuelreh could you bumb this one up please?
It's giving trouble for the operatoins team.

Thanks!
jonas
