### ISSUE TITLE
user role screen needs new copy

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#78]
While testing the new user roles feature I found that the Kudoer role needs content added but I'm having a hard time finding the dummy text in the en.yml file. Should I be able to find it there so I can update it?

<img width="1137" alt="screen shot 2016-01-26 at 1 56 03 pm" src="https://cloud.githubusercontent.com/assets/14365107/12604109/089c8512-c46d-11e5-81f6-8bf3233b2ca3.png">

**Comment by samuelreh** [comment]
https://github.com/InWithForward/sharetribe/blob/master/config/locales/en.yml#L1722
