### ISSUE TITLE
simple reply numbers for SMS

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#8]
Tested the SMS feature today and it's working great but it would be nice if the numbers were simpler for reply. Currently they are '39-45' '39-46' etc. Can they be something like 1, 2 & 3?

![sms_kudozbooking](https://cloud.githubusercontent.com/assets/14365107/10954444/3a533850-8302-11e5-8698-d68408b871c8.jpg)

**Comment by samuelreh** [comment]
Unfortunately this isn't possible. The string is actually the transaction_id-booking_id. SMS communication is actually very simple technology, so there's no way to associate a text with the previous one. If two kudoers sign up for the same listing at the same time, we wouldn't know which booking the 1 or 2 correspond to.

**Comment by lisajoytrick** [comment]
ok - no problem. Thanks!
