### ISSUE TITLE
"what's missing" mode for an experience

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#80]
We currently have experiences listed that require a Kudoz staff person to accompany a kudoer because the experience isn't ready to be done independently yet. 

These are reasons why a experience would be in coming soon mode:
1. A taster has not gone on it yet
2. The criminal record check for the host hasn't been submitted or returned
3. The experience location hasn't had a safety check.

We want to be able to flag these experiences and have that label display in "admin > view experiences" so we can be alerted and deploy a team member to go on the experience to.

Suggested solution:
Create 3 new "yes/no" admin-only fields in the experience listing [I didn't do this yet because of #79 bug] 
- Taster complete? [yes/no]
- Crim record back? [yes/no]
- Location Safety check done? [yes/no]

If any are "no" then the "coming soon" label displays on the listing (see screenshot) 
<img width="1091" alt="screen shot 2016-01-31 at 3 12 05 pm" src="https://cloud.githubusercontent.com/assets/14365107/12705898/e6204ce8-c82d-11e5-9724-34f262892964.png">

We manually deploy a team member for these experiences.

**Comment by jonaspiet** [comment]
Jonas created a new, invisible checkbox field on the Host person page:
![screen shot 2016-02-01 at 6 31 34 pm](https://cloud.githubusercontent.com/assets/11308069/12725254/0f24ea1a-c912-11e5-95c2-7daffd6a6460.png)

If not all these boxes are checked, the above described feature is to be activated in the experience transaction list.


Ideally these fields would be attached to the experience listing, but I can't make invisible / admin only fields on the experience listing. This is workable for now.

**Comment by lisajoytrick** [comment]
Here's the new screenshot for the desired admin view
<img width="1091" alt="screen shot 2016-01-31 at 3 12 05 pm" src="https://cloud.githubusercontent.com/assets/14365107/12728342/3959db60-c8d6-11e5-92f1-a5bdd08fc3d7.png">

**Comment by samuelreh** [comment]
Every experience is missing these right now. Should make them complete for all experiences?

**Comment by jonaspiet** [comment]
Thanks Sam!
@lisajoy: i think we should get Laura and Andie to update this based on
highrise? And spreadsheets?



*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by lisajoytrick** [comment]
yep - I agree. I'll let them know

**Comment by lisajoytrick** [comment]
@samuelreh how big of a deal would it be to add the "What's missing?" column to the view listings admin page? 

ie: https://catalogue.kudoz.ca/en/admin/communities/1/listings?direction=desc&sort=last_activity

**Comment by samuelreh** [comment]
This would not be hard, maybe 0.5 hrs.

**Comment by lisajoytrick** [comment]
thanks! Please proceed. :)
