### ISSUE TITLE
Make calendar more user friendly

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe#81]
Right now there are a couple of problems using the calendar.
Can you make the following adjustments of this feature?

1) ~~in 'week view', start days at 10am, and finish at 10pm.~~

2) ~~make window longer so the entire day fits in (no scrolling needed)~~

3) ~~when selecting a point in the past, with placing a recurring instance, STILL show that instance (which has passed). Right now, users don't see anything happening, and don't understand.~~

4) ~~Make the month view 'view only' (and add this to the button text). To avoid this problem: when booking an event in the 'month view', it doesn't have a time. When going to week view, it doesn't show up.~~
 
5) when selecting 'one time only' for placing a new event, display this message: 
"Please, also select one or more weekly time slots. We don't expect you to host weekly, and you can still accept or reject each request seperately. But it'll make our booking system work so much better... Thanks so much! Kudoz"

**Comment by samuelreh** [comment]
@jonaspiet I've made some modifications to the calendar. Can you play around with it a bit and let me know what you think. Also, I'm a little confused on the interaction of task 5. Could we have this text current question box, right after "Is this a weekly recurring availability or one time?".

**Comment by jonaspiet** [comment]
Thanks Sam, this works MUCH easier :)

Re: task 5: I imagined it could look like this.
If a host has only booked a one-time event, they get a pop-up message like this:


![screen shot 2016-02-01 at 8 36 27 pm](https://cloud.githubusercontent.com/assets/11308069/12728784/bb97dc92-c923-11e5-8fa7-e363cc49d769.png)

**Comment by jonaspiet** [comment]
Please also select at least one recurring availability. We don’t expect you to host weekly, but it’ll make our booking system work so much better. Thanks so much! Kudoz

**Comment by lisajoytrick** [comment]
We just got a complaint about this because a host wants to start an experience before 10 am. Can we change the start time to 8 or 8:30 maybe?

**Comment by jonaspiet** [comment]
In principle that's possible, of course...

But - it is an exotic time. It means that kudoers may have to leave around
7am or 7.30am. Can that host really not do it at 10am? or even 9am?








*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by lisajoytrick** [comment]
I think a 9 am start time is reasonable. Can we start the calendar an hour early?

**Comment by jonaspiet** [comment]
OK. lets do it.

Just let's be aware if this makes it more difficult to match kudoers and
hosts. Ideally we want to narrow down the bookable period in each day for
the period that MOST kudoers and hosts can make it.

@laura and andie: would be great to get an idea what start time of the
calendar is early enough for, say, 80% of the hosts. And if the other 20%
could really not do it a bit later. (and the same with the end time of the
calendar in the evening)

@Yani: would be great to get an idea what start time is too early for most
kudoers. Keeping in mind they have to get there too. Same for what would be
too late for most.

This will help us to make kudoers and hosts match more easily. We can't
please everyone 100%, and we have to find every way possible to make this
matching work. It'll mean we'll need less experience in the catalogue for a
certain amount of Kudoers. It might just make the difference between Kudoz
having a viable business model, or not.

thanks guys!
jonas.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet
