### ISSUE TITLE
admin to be able to manual create an experience booking

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#85]
We have experiences that are happening without a formal booking in the catalogue. Either we set it up via phone with someone (ie: learning guru schedules kudoer for a training experience) or two catalogue users have a conversation and arrange an appointment using messaging. Either way, the experience isn't officially "scheduled" in the catalogue.

Our suggested solution: 
Ability for admin to create an experience booking and assign the time/date and have it display in "view listings" like the ones users set up themselves.

please note this will be required for the mobile app to work

**Comment by lisajoytrick** [comment]
updated feature request:

From the listing page there's a new admin option to "book an experience for a user" which allows admin to choose a time & date & assign a user into the guest role & then this displays as a booked transaction on the "view experiences" page 

This prompts the confirmation emails to the host the kudoer & 48 reminder & feedback work the same way as any other confirmed transaction.

**Comment by samuelreh** [comment]
- New page with form 1 hr
- Creating booking action 1hr

**Comment by lisajoytrick** [comment]
estimate looks good - please proceed

**Comment by lisajoytrick** [comment]
This feature works great! Thanks!
