### ISSUE TITLE
deleting user doesn't work

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#87]
I'm trying to delete a few users from this screen but the deletion doesn't seem to take effect. The users still show up in the user list.

<img width="1062" alt="screen shot 2016-02-02 at 12 10 44 pm" src="https://cloud.githubusercontent.com/assets/14365107/12762931/9636f41e-c9a6-11e5-9e04-37e4056c8a02.png">

**Comment by lisajoytrick** [comment]
Can you take a look at this Sam? Not sure why it's still not working but it would be really helpful to be able to delete user accounts if it's not a bit fix.

**Comment by samuelreh** [comment]
this should work now :)
