### ISSUE TITLE
{request reason} field added to booking sequence

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#89]
When a Kudoer is booking an experience they will see another question between the time choices and confirm button. This field is called {request reason} and should be available via API to mobile app.

**Content:**
I choose this experience, because I want to:
(select the top reason)
- explore an interest in [experience category]
- challenge myself
- find out about jobs in [experience category]
- connect with the host, [host name]
- have fun
- something else? write your answer here… [open text field]

The data will be stored as plain text so that if the options change over time we don't loose the data.

Proposed layout:
![screen shot 2016-02-03 at 2 32 59 pm](https://cloud.githubusercontent.com/assets/11308069/12783665/1919008e-ca83-11e5-85c4-37995910d772.png)

**Comment by lisajoytrick** [comment]
The phrasing in my screenshot is a bit off. Go with the text written above.

**Comment by mkasdani** [comment]
Looks great!
Can we change it to "I am choosing this experience because I want to...."
then the dropdown menu. Right now it doesn't make a sentence.
Just a small detial.

**Comment by jonaspiet** [comment]
Let's make this feature a separate screen, after choosing the time slots.
(Otherwise it conflicts with #83 Improve requesting experience dialogue)

![screen shot 2016-02-03 at 1 20 04 pm](https://cloud.githubusercontent.com/assets/11308069/12782066/0d0874c8-ca79-11e5-9036-84bb9e8fa87d.png)

**Comment by samuelreh** [comment]
- New page carrying over state from previous page: 1 hr
- Selector with options 0.5 hr
- Open text field form 1 hr
- New DB text field on transactions 0.5 hr

**Comment by lisajoytrick** [comment]
Approved. Please proceed.

**Comment by samuelreh** [comment]
This is on staging, If you like it I can deploy it.

**Comment by lisajoytrick** [comment]
Works great! Let's deploy.

**Comment by lisajoytrick** [comment]
Can we add the {request reason} field to the kudoer's confirmation page about the experience?
