### ISSUE TITLE
Show 'request expired' in Experience view panel, if host doesn't respond in 48h

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe#91]
As an admin, I want to be able to see it if hosts didn't accept or cancel a (formal) experience booking request after 48h.  Can we create a new status, and update this in the View Experience panel?

![screen shot 2016-02-03 at 2 54 14 pm](https://cloud.githubusercontent.com/assets/11308069/12784224/110bf7a4-ca86-11e5-9887-68ce9400b274.png)

**Comment by samuelreh** [comment]
Hmmm, right now it is canceled if not requested in time. You're saying you want another state that is basically 'expired' instead. To be clear, when should this expired state happen?

**Comment by samuelreh** [comment]
Experiences will now expire if they haven't been accepted or rejected in time. :smiley:

**Comment by jonaspiet** [comment]
cool. that time should be 48h.

If  48h after a request a booking isn't rejected / accepted by the host it
is *'expired'.*

The idea is that we get in touch with the host to see why they didn't
respond.
So after expiring, there's another 48h before the request is

*'canceled'.*
Jonas.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
oh. rather than having a state, could we just show the time of the bookings?

**Comment by jonaspiet** [comment]
as long as it's clear for a viewer, which ones need action.
so if it only shows times of the ones that are 'expired' or overtime, that
would work.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet

**Comment by samuelreh** [comment]
Ok, sorry for the confusion, to be clear, the desired functionality is:
1. Experience is booked.
2. if not responded to after 48 hours from booking time, it is marked as expired in the admin (but the state  for the users doesn't change)
3. 96 hours after the bookings time, if not responded to, we cancel the booking.
