### ISSUE TITLE
question - admin posting experience for another user

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#94]
Is there any way for an admin to post an experience for another user?

**Comment by samuelreh** [comment]
Don't think so. This might be another good reason for a skeleton key.

**Comment by lisajoytrick** [comment]
I've tried wikipedia-ing what a skeleton key is and all I'm getting is films and a description of a metal key that opens lots of things. Help!

**Comment by samuelreh** [comment]
haha skeleton key is a way to log into any account basically as if you were them.

**Comment by lisajoytrick** [comment]
ah. that sounds perfect.
