### ISSUE TITLE
closed listings - how to see them

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#95]
We would like a way to see a list of the closed listings. Is this already available to us somewhere? 

If not, could we get an estimate on this?

**Comment by jonaspiet** [comment]
I'm downloading the CSV from the View Experiences page, and can sort the 'status' column. It works well. Good enough for now, I think?

**Comment by lisajoytrick** [comment]
Yep - that's what we used for the dashboard this week and it worked well.



On Feb 8, 2016, at 2:05 AM, jonaspiet <notifications@github.com> wrote:

I'm downloading the CSV from the View Experiences page, and can sort the
'status' column. It works well. Good enough for now, I think?

—
Reply to this email directly or view it on GitHub
<https://github.com/InWithForward/sharetribe/issues/95#issuecomment-181285148>
.

**Comment by lisajoytrick** [comment]
I mean, it worked well for sorting out which experiences we're ready to go but I can't see a way to get the closed experiences from this export. You?

**Comment by lisajoytrick** [comment]
done :)
