### ISSUE TITLE
Add "mark experience as done" and "cancel" buttons to the hosts message/confirmation page (part 2)

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#97]
Feature request part 2: Add "mark experience as done" and "cancel" buttons to the hosts message/confirmation page.

Background:
After an experience is confirmed some information displays on the hosts message and some options display on the kudoers message. Can we get everything to display on both?

<img width="1218" alt="screen shot 2016-02-09 at 2 26 47 pm" src="https://cloud.githubusercontent.com/assets/14365107/12933019/ba99b01e-cf3a-11e5-89c9-4ddd16675d19.png">

**Comment by lisajoytrick** [comment]
Can we expedite this at all? It's causing some confusion for us in the admin panel that hosts can't cancel an experience.

**Comment by samuelreh** [comment]
Add buttons / Add actions for buttons - 0.5 hr
Add/modify services that handle cancellation / confirmation by host - 1hr
1.5 hr total

**Comment by lisajoytrick** [comment]
approved

**Comment by lisajoytrick** [comment]
Hey Sam,

Tried this out and the only thing that seems a bit weird is that it shows that even though I as a host pressed the cancel button, it shows that the person who booked the experience (the Kudoer) cancelled it in the message stream. Not super big deal but maybe a bit confusing?

<img width="1280" alt="screen shot 2016-02-14 at 1 54 49 pm" src="https://cloud.githubusercontent.com/assets/14365107/13040817/bdcca28a-d365-11e5-9fda-8c093e4969f1.png">

**Comment by samuelreh** [comment]
Totally agree, unfortunately Sharetribe doesn't keep track of who performed the action. It just assigns the actor based on the action type, but in our case, now that both parties can cancel or confirm, it doesn't display correctly. 

We have several options:
- We can save the actor on transitions and display the bubble things based on that. 
- We can remove the person from cancel and confirm (at least then it would reflect the fact that we really don't know who did it).
- Or we could ignore it for now.
