### ISSUE TITLE
Interest tags

### ISSUE THREAD

**Issue by jonaspiet** [InWithForward/sharetribe#98]
to add to profile: users can create tags to add to their profile. And delete.
Record when  tags are added / deleted, so we can changes. 
These tags are shown on a profile page.

**Comment by samuelreh** [comment]
@jonaspiet I'm curious what the motivation for this is. What's the difference between this and a text field that asks for interests?

**Comment by samuelreh** [comment]
This is done, however tracking is not in place yet.

**Comment by jonaspiet** [comment]
thanks @samuelreh !

motivations /  assumptions: I am hoping to see this change more often then a story. It is easier to add/change for kudoers, and easier to see/track specific changes for us. I am also hoping that this makes the profile look more diverse, nit just blocks of text.

Could you make a few tweaks:
- make each tag appear on a new line, or something else to clearly separate them from one another (see screenshot)
- make the tags more bold/a little bigger

![screen shot 2016-02-25 at 12 11 45 pm](https://cloud.githubusercontent.com/assets/11308069/13318077/02d2faf4-dbb9-11e5-99ec-263d1ea37fea.png)

**Comment by samuelreh** [comment]
@jonaspiet how's this for now: <img width="618" alt="screen shot 2016-02-29 at 10 13 08 am" src="https://cloud.githubusercontent.com/assets/128012/13404145/2fcfd4d4-decd-11e5-9689-a9f164ad6bf6.png">

I'm tracking these changes now, I'm not sure how we want to display the tracked changes though. Or is showing them in Mixpanel good enough for now?

**Comment by jonaspiet** [comment]
@samuelreh: sorry for the slow response!
can find an easy way to show to users the ones they deleted (e.g. gray-ed
out, striked-through, ...)?
that would be great.

if this is not easy - let's talk tomorrow.


*Jonas Piet*

*Partner & Lead Service Designer InWithForward*
MOBILE +31(0)6 1604 1176
SKYPE jonaspiet
