### ISSUE TITLE
Header button for returning to the front of the catalogue

### ISSUE THREAD

**Issue by AndieFro** [InWithForward/sharetribe#99]
Can the "Kudoz" button on top of the catalogue point back to catalogue.kudoz.ca (instead of kudoz.ca)?

I've had team members, and several hosts comment on this being a challenge.

When viewing an experience and a user wants to return to the main page of the catalogue the "Kudoz" button at the top left redirects users to kudoz.ca when most users are hoping to return to catalogue.kudoz.ca. Is there a way to add a header button at the top of experience listing pages that says something like "return to the catalogue".

**Comment by jonaspiet** [comment]
@samuelreh would you be able to make this swiftly?
Thanks!

**Comment by samuelreh** [comment]
How bout a button that says catalogue to the right of the logo. It's easiest just to put it on every page if that's alright?

**Comment by AndieFro** [comment]
yep, that would be great

**Comment by mkasdani** [comment]
Hi Sam,

Thanks for adding the 'catalogue' button.

I tested it with my phone, it's still unclear for me of how Kudoers can go back to the catalogue.
This is what it looks like on my phone screen right now.
![catalogue1](https://cloud.githubusercontent.com/assets/16656508/13163890/854cb014-d665-11e5-9345-24458cd6016e.png)

Now I know I have to click the O button and click "home" to go back to the catalogue.
![catalogue2](https://cloud.githubusercontent.com/assets/16656508/13163925/dfb67f58-d665-11e5-868f-48f60a307fdf.png)

Can we switch this around please? So the yellow K box is 'back to catalogue', and the house icon for 'home' is to go back to 'www.kudoz.ca' ?

And we do the same for the website version?

Thanks!

**Comment by mkasdani** [comment]
Made a mock up for the website version. I don't know whether this is simple/ difficult. If it's too difficult, let's just have it as a text: 'home' and 'catalogue'

![screenshot 2016-02-18 17 57 28](https://cloud.githubusercontent.com/assets/16656508/13164340/4ee11606-d669-11e5-8c65-713736b3165c.png)

**Comment by jonaspiet** [comment]
@mkasdani : i think what Sam made solves the problem.
on your phone, click on the 'home' button to go back to the front page.
